services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_db_vol:/var/lib/mysql
      - ./mysql:/app
  mongodb:
    image: mongo:7.0.1
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongodb_configdb_vol:/data/configdb
      - mongodb_db_vol:/data/db
      - mongodb_log_vol:/var/log/mongodb
      - ./mongodb:/app

volumes:
  mongodb_configdb_vol:
  mongodb_db_vol:
  mongodb_log_vol:
  mysql_db_vol:
